
//! Autogenerated weights for pallet_poe
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-24, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `baru-pc`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_poe
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/poe/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_poe.
pub trait WeightInfo {
	fn create_claim(d: u32, ) -> Weight;
	fn revoke_claim(d: u32, ) -> Weight;
	fn transfer_claim(d: u32, ) -> Weight;
}

/// Weights for pallet_poe using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(85), added: 2560, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 32]`.
	fn create_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3550`
		// Minimum execution time: 18_726_000 picoseconds.
		Weight::from_parts(22_456_948, 3550)
			// Standard Error: 33_430
			.saturating_add(Weight::from_parts(5_717, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(85), added: 2560, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 32]`.
	fn revoke_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85 + d * (1 ±0)`
		//  Estimated: `3550`
		// Minimum execution time: 18_275_000 picoseconds.
		Weight::from_parts(20_024_831, 3550)
			// Standard Error: 17_219
			.saturating_add(Weight::from_parts(36_145, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(85), added: 2560, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 32]`.
	fn transfer_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85 + d * (1 ±0)`
		//  Estimated: `3550`
		// Minimum execution time: 20_369_000 picoseconds.
		Weight::from_parts(22_422_690, 3550)
			// Standard Error: 24_359
			.saturating_add(Weight::from_parts(46_365, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(85), added: 2560, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 32]`.
	fn create_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3550`
		// Minimum execution time: 18_726_000 picoseconds.
		Weight::from_parts(22_456_948, 3550)
			// Standard Error: 33_430
			.saturating_add(Weight::from_parts(5_717, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(85), added: 2560, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 32]`.
	fn revoke_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85 + d * (1 ±0)`
		//  Estimated: `3550`
		// Minimum execution time: 18_275_000 picoseconds.
		Weight::from_parts(20_024_831, 3550)
			// Standard Error: 17_219
			.saturating_add(Weight::from_parts(36_145, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: PoeModule Proofs (r:1 w:1)
	/// Proof: PoeModule Proofs (max_values: None, max_size: Some(85), added: 2560, mode: MaxEncodedLen)
	/// The range of component `d` is `[0, 32]`.
	fn transfer_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85 + d * (1 ±0)`
		//  Estimated: `3550`
		// Minimum execution time: 20_369_000 picoseconds.
		Weight::from_parts(22_422_690, 3550)
			// Standard Error: 24_359
			.saturating_add(Weight::from_parts(46_365, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
